spring.application.name=site-ecommerce

server.port=${SERVER_PORT:8081}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/site_ecommerce?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

### Authentification
jwt.secret=${JWT_SECRET}
jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}

### envoi des emails
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USER}
spring.mail.password=${GMAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

### gestion des images avec cloudinary
cloudinary.url=${CLOUDINARY_URL}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB