apiVersion: v1
kind: Service
metadata:
  name: site-ecommerce-backend-service
  namespace: site-ecommerce
spec:
  type: LoadBalancer
  selector:
    app: site-ecommerce-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081